services:
  - type: web
    name: restaurant_preorder
    env: python
    buildCommand: "pip install -r ./requirements.txt"
    startCommand: "gunicorn restaurant_preorder.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: restaurant_preorder_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: restaurant_preorder_db
    databaseName: restaurant_preorder
    user: restaurant_preorder
